# examples:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_cleanup_with_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day
development:
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: "12 */1 * * *"

  recalculate_balances_job:
    command: "RecalculateBalancesJob.perform_now"
    schedule: "*/5 * * * *"

  update_vacation_request_job:
    command: "UpdateVacationRequestJob.perform_now"
    schedule: "0 0 * * *"

production:
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: "12 */1 * * *"

  recalculate_balances_job:
    command: "RecalculateBalancesJob.perform_now"
    schedule: "*/5 * * * *"

  update_vacation_request_job:
    command: "UpdateVacationRequestJob.perform_now"
    schedule: "0 0 * * *"
