name: Deploy Digital Ocean

on:
  push:
    branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    env:
      BUNDLE_RUBYGEMS__PKG__GITHUB__COM: ${{ secrets.BUNDLE_RUBYGEMS__PKG__GITHUB__COM }}
      HOME: -/root
      XDG_CONFIG_HOME: "/runner/_work/.config"
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set Tag docker
        run: |
          echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
      - name: GitHub Action for DigitalOcean - doctl
        uses: digitalocean/action-doctl@v2.5.1
        with:
          token: ${{ secrets.DIGITALOCEAN_PIBOX_ACCESS_TOKEN }}
      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600
      - name: 'Install dependencies'
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl
          kubectl version --client
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: |
            BUNDLE_RUBYGEMS__PKG__GITHUB__COM=${{ secrets.BUNDLE_RUBYGEMS__PKG__GITHUB__COM }}
            RAILS_ENV=production
            COMMIT=${{ github.sha }}
          push: true
          tags: registry.digitalocean.com/pibox/picap_rh:${{ env.BRANCH_NAME }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
